### ISSUE TITLE
send cli command but get timeout

### ISSUE THREAD

**Issue by longnehc** [scrapli/scrapligo#113]
Hi,

I defined a new platform for my switch. It works well but today I sent a command 'display current-configuration configuration bgp' and got: 

failed to send input to device; error: errTimeoutError: channel timeout sending input to device
panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
scrapligo/util.(*Queue).Dequeue(0xc00009b8c0)
        /scrapligo/util/queue.go:64 +0x1cb
scrapligo/channel.(*Channel).ReadUntilExplicit(0xc0000da360, {0xc0001e8060, 0x2f, 0x30})
       /scrapligo/channel/read.go:167 +0x9e
scrapligo/channel.(*Channel).ReadUntilInput(...)
        /scrapligo/channel/read.go:94
scrapligo/channel.(*Channel).SendInputB.func1()
        /scrapligo/channel/sendinput.go:31 +0xc8
created by scrapligo/channel.(*Channel).SendInputB
        /scrapligo/channel/sendinput.go:21 +0x1f0

Process finished with the exit code 2

I debugged on the switch side. I find the switch successfully received the command, but the ssh connection was broken. Do you know how I can fix it?

Here is the switch log:
SSHS/6/SSHS_AUTH_SUCCESS: SSH user netcontroler from XXX port 64880 passed password authentication.
SSH user netcontroler (IP: XXXX) connected to the server successfully.
SHELL/5/SHELL_LOGIN: netcontroler logged in from 10.4.34.232.
SHELL/6/SHELL_CMD: -Line=vty1-IPAddr=XXX-User=netcontroler; Command is screen-length disable
SHELL/6/SHELL_CMD: -Line=vty1-IPAddr=XXX-User=netcontroler; Command is display ip vpn-instance
SHELL/6/SHELL_CMD: -Line=vty1-IPAddr=XXX-User=netcontroler; Command is display current-configuration configuration bgp
SSHS/6/SSHS_DISCONNECT: SSH user netcontroler (IP: XXX) disconnected from the server.
SHELL/5/SHELL_LOGOUT: netcontroler logged out from XXX.

**Comment by carlmontanari** [comment]
If I had to guess it's due to a long command string and you not disabling terminal width or some type of cli tab complete (like Junos does) Logs would probably show this w/ some ansi characters interrupting your input command. So, tl;dr if everything else works its almost certainly a problem w/ your custom platform. I'll close this for now since I'm pretty positive thats the case -- if you get logs and find some scrapligo related issue please feel free to reopen, but if you do, please format output nicely (triple back ticks, top left key under escape key on US keyboards or the code block box thing in the editor here) so it is easier to read.
