### ISSUE TITLE
do we need to create an empty response object in case of a failed acquire privelege?

### ISSUE THREAD

**Issue by hellt** [scrapli/scrapligo#13]
In here you create a response object where only host, port and command fields are populated
https://github.com/scrapli/scrapligo/blob/379e44c4b71756b578208c9056b22114eccf1b94/driver/network/sendcommand.go#L13-L16

is there a need for that? Won't `nil` be enough in that case?

**Comment by carlmontanari** [comment]
Thats a good question.... so... the reason I did it like this is that we *always* return a response object in python-land. If the thing is failed we return a response object marked as failed, if it works obv we return a response object that is good. 

That is/was at least my thinking... but now that you mention it and I think about it... I think that you are correct that this could just be nil here (and probably in all the other send methods) because this would be more equivalent to us hitting an exception in python and just getting a stack trace. I'll go ahead and fix this and get it pushed shortly :) Good call!

**Comment by carlmontanari** [comment]
Change made [here](https://github.com/scrapli/scrapligo/commit/8a87b1273735fa44cdb3c321e74b02a14894491e). I think this looks nicer, what do ya think?

**Comment by hellt** [comment]
yes, thanks!
