### ISSUE TITLE
can't build app for windows if the app uses netconf driver 

### ISSUE THREAD

**Issue by idqdq** [scrapli/scrapligo#55]
Hi Carl 
this is the follow-up issue I've described in the [issue 54](https://github.com/scrapli/scrapligo/issues/54#issue-1051877593)

the next issue I ran into - I can't build my app for windows platform
to be honest I've never tried it before so maybe I'm doing something wrong

this is what i was trying to do and the result

```bash
> GOOS=windows GOARCH=amd64 go build clear_ipsec.go
# github.com/scrapli/scrapligo/driver/base
../../driver/base/new_windows.go:43:22: d.TimeoutSocket undefined (type *Driver has no field or method TimeoutSocket)
../../driver/base/new_windows.go:44:22: d.TimeoutTransport undefined (type *Driver has no field or method TimeoutTransport)

```

my code
```go
       d, _ := netconf.NewNetconfDriver(
		"192.168.99.94",
		base.WithAuthStrictKey(false),
		base.WithAuthUsername("clear_ipsec"),
		base.WithAuthPassword("strongpassword"),
		base.WithPort(22),
		//base.WithTimeoutTransport(20),
		//base.WithTimeoutSocket(20),
		base.WithTransportType(transport.StandardTransportName),
	)

	d.Open()
```
as you can see I've tried to play with Timeouts (commented out) but with no success

**Comment by carlmontanari** [comment]
:wave:

Hey Nikolay!

I'll respond to the other issue probably this weekend, but this one was easy enough 😁 

You're lucky this was an easy one since I don't care at all about windows hahah. Anyway, just pushed a commit to main branch that should sort it out. Basically was just some cruft that was left over from overhauling some of the transport stuff a few months back. Since I don't care about/test/support windows (and never will!!!!! 🤣 ) it got missed.

Let us know if [this commit](https://github.com/scrapli/scrapligo/commit/4f3a35e04f96f159080d033ce93a18debd1f2bb6) sorts it out. Basically just setting the defaults instead of assigning from driver object -- then the options get applied toward the end of that function.

Carl

**Comment by idqdq** [comment]
Hi Carl
Yes it does work now
Thx

p.s I like your attitude to windows :)

**Comment by carlmontanari** [comment]
Awesome, thanks for confirming!
