### ISSUE TITLE
data race in channel

### ISSUE THREAD

**Issue by networkop** [scrapli/scrapligo#56]
When using scrapligo from goroutines, go detects a race:

```
go run -race main.go
==================
WARNING: DATA RACE
Write at 0x000000a5f190 by goroutine 9:
  github.com/scrapli/scrapligo/channel.getAuthPatterns()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:21 +0x144
  github.com/scrapli/scrapligo/channel.(*Channel).authenticateSSH()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:34 +0x294
  github.com/scrapli/scrapligo/channel.(*Channel).AuthenticateSSH.func1()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:120 +0xc4

Previous read at 0x000000a5f190 by goroutine 10:
  github.com/scrapli/scrapligo/channel.getAuthPatterns()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:20 +0x30
  github.com/scrapli/scrapligo/channel.(*Channel).authenticateSSH()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:34 +0x294
  github.com/scrapli/scrapligo/channel.(*Channel).AuthenticateSSH.func1()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:120 +0xc4

Goroutine 9 (running) created at:
  github.com/scrapli/scrapligo/channel.(*Channel).AuthenticateSSH()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/channel/authenticate.go:119 +0x1ea
  github.com/scrapli/scrapligo/driver/base.(*Driver).Open()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/driver/base/base.go:74 +0x631
  github.com/scrapli/scrapligo/driver/network.(*Driver).Open()
      /home/mk/go/pkg/mod/github.com/scrapli/scrapligo@v0.1.1/driver/network/network.go:82 +0x32
  main.getVersion()
      /home/mk/Network-Automation-with-Go/ch03/concurrency4/main.go:48 +0x544
  main.main·dwrap·4()
      /home/mk/Network-Automation-with-Go/ch03/concurrency4/main.go:114 +0x109

```

Can I suggest replacing 

```go
func getAuthPatterns() *authPatterns {
	if authPatternsInstance == nil {
		authPatternsInstance = &authPatterns{
			telnetLoginPattern: regexp.MustCompile(`(?im)^(.*username:)|(.*login:)\s?$`),
			passwordPattern:    regexp.MustCompile(`(?im)^(.*@.*)?password:\s?$`),
			passphrasePattern:  regexp.MustCompile(`(?i)enter passphrase for key`),
		}
	}

	return authPatternsInstance
}
```

with

```go
func init() {
	if authPatternsInstance == nil {
		authPatternsInstance = &authPatterns{
			telnetLoginPattern: regexp.MustCompile(`(?im)^(.*username:)|(.*login:)\s?$`),
			passwordPattern:    regexp.MustCompile(`(?im)^(.*@.*)?password:\s?$`),
			passphrasePattern:  regexp.MustCompile(`(?i)enter passphrase for key`),
		}
	}

}
```

with these changes race is not detected.

**Comment by hellt** [comment]
I think the CI linters scrapligo uses will bark on `init` functions (aka global vars); hence everything has been scoped to functions.
Another way to solve this would be to put a `mutex.Lock` in that function.

**Comment by networkop** [comment]
yeah, ok. whatever works. I guess it should also be possible to wrap it in `once.do()`

**Comment by hellt** [comment]
@networkop the piece of code to test it locally would be something like

* create two goroutines
* in each goroutine, create a driver and send cmd
?

**Comment by networkop** [comment]
yes, for example `go run -race main.go` from  https://github.com/PacktPublishing/Network-Automation-with-Go/tree/main/ch03/concurrency3/

**Comment by carlmontanari** [comment]
Ahh neat! Yeah, Roman is right -- since this is my first real go project I really leaned hard into the linters to try to help me know what *not* to do... and yea, they complained a lot about globals and stuff -- even in this instance there is the global for the patterns that is being ignored though so maybe `init` is a totally acceptable option? I *think* there are also going to be some others like [this](https://github.com/scrapli/scrapligo/blob/40ed54b60468d8c3867561598a9b8f55f590b511/cfg/juniperjunos.go#L19-L30) that may need to get the same fixup treatment.

So.... what is the "most right" way to fix it? I'm down `init`, a lock feels heavy handed but I'm game for that, and `once.do` sounds fancy/simple but is that common/"idiomatic"? I don't have enough smarts around this to have a strong preference I think, but am super keen to get this all fixed up, so lookin forward to see what ya'll think is the best way to sort this out!

Thanks for raising this Michael, appreciate it! (and thanks Roman for being involved as always!)

Carl

**Comment by hellt** [comment]
I am not smart pants here either
this might help to decide which way to go (oops) init() vs once.do - https://stackoverflow.com/a/51954101

**Comment by hellt** [comment]
fwiw, if those patterns are not meant to be changed by the users, I'd keep them as global vars and silence the linter =)

**Comment by carlmontanari** [comment]
Ah that link is helpful, thanks dude! I kinda like the `once` thing because the patterns are unnecessary unless they aren't haha. What I mean by that is for the channel auth patterns and also for the patterns in "cfg" they only need to be compiled if/when the user uses system transport or the given "cfg" platform.

I think that makes sense/feels good 🤷

**Comment by networkop** [comment]
yeah, i think that if what you wanted was to do lazy evaluation in Go, then once.Do is the right tool for the job https://blog.merovius.de/2015/07/17/lazy-evaluation-in-go.html
https://stackoverflow.com/a/53504651/14231016
http://marcio.io/2015/07/singleton-pattern-in-go/

**Comment by carlmontanari** [comment]
Ok awesome! Thank you gents! I'll poke this sometime later in the week and will let ya'll know how it goes!

**Comment by carlmontanari** [comment]
closing this -- will finish hashing this out in the pr!
