### ISSUE TITLE
ssh handshake failed: no common algorithm for key exchange

### ISSUE THREAD

**Issue by Bofrostmann07** [scrapli/scrapligo#77]
Hey Carl,

i'm trying to access an old Cisco C3560. I get the following error message.
I´ve seen that there is no way to set the kexalgorithms. 

```failed to open driver; error: ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1], server offered: [diffie-hellman-group1-sha1]```

I´ve lookup in the ssh package, that you can set the kexalgorithms up:
https://pkg.go.dev/golang.org/x/crypto/ssh#Config
--> KeyExchanges []string

Im more then happy to test a new build, if we can come up with a solution :)

Regards,
Romario

**Comment by carlmontanari** [comment]
Hey @Bofrostmann07 !

If you are doing this with the default transport the fastest fix is to point to an ssh config file and enable the kexts there (default/system transport is just a magical /bin/ssh wrapper, so "normal" openssh things apply here). Off the top of my head we dont support passing transport options ad-hoc to the system transport in scrapligo (yet) like we do in scrapli (python) though, so you would need to do the config file route.

If you are using standard transport, yeah, no work around for that at this point.

Either way, yea, we need to get this sorted in scrapligo at some point. I am hoping to do a fairly big overhaul / cleanup soon.... but I'm not 100% sure how soon soon is 😁 if/when that happens I'll make sure to get this sorted. In the meantime if you are up for a pr to sort this out, im happy to review/merge.

Carl

**Comment by dpnetca** [comment]
can confirm I had similar issues a while ago...


sshconfig file worked for me...driver setup code:
```
 driver, err := core.NewCoreDriver(
                device.Hostname,
                device.Device_type,
                base.WithAuthStrictKey(false),
                base.WithAuthUsername(device.Username),
                base.WithAuthPassword(device.Password),
                base.WithTimeoutOps(10*time.Second),
                base.WithTransportType("standard"),
                base.WithSSHConfigFile("/home/<xxx>/.ssh/config"),
        )
```
and then had this added to be config file:
```
HOST 192.168.118.202
  KexAlgorithms +diffie-hellman-group14-sha1
```

I have this with the transport type standard and I think it worked...have a comment block elsewhere in the code where I was testing something else w/ transport type as system, but I believe this worked with both

**Comment by d-Rickyy-b** [comment]
> [...] and I think it worked...

Sadly this only seems to works non Windows systems and the "system" transport type.

https://github.com/scrapli/scrapligo/blob/cbcb0c96c5b7948b5c12bb7d6ea67beecd4d3f53/transport/system.go#L1-L2

https://github.com/scrapli/scrapligo/blob/cbcb0c96c5b7948b5c12bb7d6ea67beecd4d3f53/transport/system.go#L104-L110

The "standard" transport type doesn't seem to do anything with the SSHConfigFile at all. At least I couldn't get any hits on the GitHub search: https://cs.github.com/scrapli/scrapligo?q=configFile

**Comment by carlmontanari** [comment]
> Sadly this only seems to works non Windows systems

as an FYI, scrapli/scrapligo will never officially "support" windows -- if it works on windows cool, but thats as far as it goes.

> systems and the "system" transport type.

Yea, "system" transport (default) Is just a magic wrapper around /bin/ssh, so 100% of normal system openssh things are supported. "standard" transport *shouldnt* (probably?) need to have any tweaks for cipher/kext/etc. anyway, so this shouldn't be relevant there (though I could be very wrong on that!).

> The "standard" transport type doesn't seem to do anything with the SSHConfigFile at all

Yeah, in current state, I believe you are correct. in python version we do a *little* bit of ssh config file parsing and that could get brought into scrapligo at some point --  but would need to figure out what is relevant and/or possible here... the big two would be proxy jump and control persist probably and I dont know off hand how much of that is supported by crypto/ssh

**Comment by d-Rickyy-b** [comment]
> > Sadly this only seems to works non Windows systems
> 
> as an FYI, scrapli/scrapligo will never officially "support" windows -- if it works on windows cool, but thats as far as it goes.

Thanks for the info. That's understandable but sad, given that go is a platform independent language on its own and that there are ssh packages available. But I get that you might not want or aren't able to support Windows. Whatever reasons you got, they are probably valid.

> > systems and the "system" transport type.
> 
> Yea, "system" transport (default) Is just a magic wrapper around /bin/ssh, so 100% of normal system openssh things are supported. "standard" transport _shouldnt_ (probably?) need to have any tweaks for cipher/kext/etc. anyway, so this shouldn't be relevant there (though I could be very wrong on that!).

Well, as always, it's complicated. There is quite a lot of older network hardware that still uses ciphers and kex algorithms which are no longer offered by the ssh package by default. You need to explicitly state that you want to include 
for example `diffie-hellman-group1-sha1` or `aes128-cbc`. Of course the underlying issue is the (out)dated hardware. But sadly the reality is that companies still use (out)dated network hardware. Coming from an infosec background myself this makes me very sad - but sadly it is the reality. And currently, accessing such hardware is not possible using scrapligo.

Even the Cisco C3560 (End of support: May 2021) mentioned in this issue cannot be accessed without manipulating the kex and ciphers (assuming there is no ssh config @Bofrostmann07 missed to update to a more secure kex & cipher on the switch).

But of course, it can be a (valid) decision to not further support such devices. I'm just trying to document our experiences with the library :)

**Comment by carlmontanari** [comment]
>  You need to explicitly state that you want to include
for example diffie-hellman-group1-sha1 or aes128-cbc. 

is this true w/ crypto/ssh (meaning "standard" transport)? I have yet to run into a device (and you mentioned a 3560, that is what I run at my house 😁) which of course has outdated ciphers/kext. For "system" I of course need to add the cipher/kext via config file or transport options, but "standard" ive not seen complain about this yet. 

I'm working on a "v1.0.0" of scrapligo at this very moment, and ideally I will get "standard" transport a bit more love, so just trying to understand if that is something that needs to get exposed for that transport option. 

RE the windows stuff -- thanks for being understanding. I am like 99.9% sure that windows will work with the standard transport (and continue to work), and I will make sure that users dont *require* creak/pty (what enables the "system" transport, but is not supported on windows), so in theory windows will work, I just am not going to waste my time actively supporting it as I hate windows with a fiery passion 🤣

**Comment by d-Rickyy-b** [comment]
> > You need to explicitly state that you want to include
> > for example diffie-hellman-group1-sha1 or aes128-cbc.
> 
> is this true w/ crypto/ssh (meaning "standard" transport)? I have yet to run into a device (and you mentioned a 3560, that is what I run at my house 😁) which of course has outdated ciphers/kext. For "system" I of course need to add the cipher/kext via config file or transport options, but "standard" ive not seen complain about this yet.

I helped @Bofrostmann07 with the setup of scrapligo and his 3560. The code we wrote and ran on a Windows client we tested from only offered the kex algorithms listed in the original issue but not `diffie-hellman-group1-sha1`, which seems to be the only kex algorithm the switch supports.

We tried again by directly connecting to the switch by using /x/crypto/ssh. We explicitly needed to add the missing kex algorithm.

```
kexConfig.KeyExchanges = append(kexConfig.KeyExchanges, "diffie-hellman-group1-sha1")
```

I am not a network engineer, so I have no idea if there are further options we can manipulate or configurations one can change so that the switch accepts a bit more modern kex/ciphers. If it works for you, that's the only variable I can currently come up with.

> RE the windows stuff -- thanks for being understanding. 

This project is offered for free (using the MIT license) and you are (probably) using your free time to work on it. I can express my feelings and opinions but eventually I must accept your decisions - because well, it's **your** time that goes into this.

**Comment by carlmontanari** [comment]
> We tried again by directly connecting to the switch by using /x/crypto/ssh. We explicitly needed to add the missing kex algorithm.

Cool, this is perfect, the eventually (hopefully sooner than later!) 1.0.0 version of scrapligo will support this!

**Comment by d-Rickyy-b** [comment]
Great :) - just as a heads up, we also needed to add some ciphers along with the kex.

```
kexConfig.Ciphers = append(kexConfig.Ciphers, "aes128-cbc", "3des-cbc", "aes192-cbc", "aes256-cbc")
```

I need to admit that we did not explicitly check which one of these were needed by the switch, so we simply added all of them.
Adding these by default may make your code susceptible for downgrading attacks - so maybe make this an optional feature one explicitly needs to enable?

Thanks for your time and work :) Cheers!

**Comment by carlmontanari** [comment]
Yep, makes sense. This will be an optional thing so we are more sane/safe by default! Thanks for all the details, will keep this open to make sure this gets into v1.0.0!

**Comment by carlmontanari** [comment]
ive not pushed anything, but the v1.0.0 stuff im working on now supports adding additional cipher/kext in the standard transport so I'm going to go ahead and close this. hoping for ~1mo or so until 1.0.0 release where this will be.

thanks again ya'll!

Carl

**Comment by KeithETruesdell** [comment]
I was having the same issue, this is a great thread.
I created a local file to the Go app I was working on, and just named it `ssh_config` and put the following in it...
```
HOST *
  KexAlgorithms +diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
  Ciphers +aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc  
```
