### ISSUE TITLE
Incorrect chunk matching with netconf 1.1 (and ## in output)

### ISSUE THREAD

**Issue by netixx** [scrapli/scrapligo#99]
Hello,

I have an issue while reading a device config, using a simple `GetConfig("running")`: the output returned by `Result` is truncated.
Looking further, It's truncated here:
```
<next-hops>
         <next-hop>
          <index
```

The original data returned by the device is visible in the logs:
```
      <next-hops>
         <next-hop>
          <index>##10.222.18.65##</index>
```

We can see that the output is truncated at the `##` character.

I think the issue lies with the `record1dot1()` function (since the router is using netconf 1.1), 
In particular,
```
chunkSections := patterns.v1dot1Chunk.FindAllSubmatch(r.RawResult, -1)
```
is cutting the final chunk at the `<index>`  tag.

I can see with the debugger that the final chunk has length 45100, but it's size should be 106234. This sets the r.Failed (which I didn't notice before investigating this issue).

I therefore think that the `v1dot1Chunk` is wrong. A chunk on my device looks like this:
```
#106234
  <netconf-yang xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-um-netconf-yang-cfg">
   <agent>
    <ssh/>
   </agent>
  </netconf-yang>
```
and the pattern is ``v1dot1Chunk: regexp.MustCompile(`(?ms)(\d+)\n(.*?)#`),``.

I had success on this router by changing the pattern to `(?ms)(\d+)\n(.*?)^#`, but I don't know if it breaks other things.

**Comment by hellt** [comment]
@netixx looks like this is on XR
do you have other routers to try your fixed pattern with?

**Comment by carlmontanari** [comment]
I am like... 99% sure this was set this way for a reason... but of course I dont remember what that reason is anymore 😂 

I wonder if something like `(?ms)(\d+)\n(.*?)^\s?#` would at least be a bit "safer", as in less strict, so hopefully less possibility of breaking things. I wonder also if we could do it more like scrapli python where we simply find the chunk sizes with a regexp then slice out that amount of characters. I feel like I thought this regexp way was an improvement, but maybe I was wrong!

In any case, for this, I'm quite happy to defer to the two of ya'll since I dont do anything with netconf at this point and have no real way to test other than the small clab setup I have (that of course passes as is or I would have changed things!).

Thoughts?

**Comment by hellt** [comment]
I can check the proposed regexp on SR OS and likely on Arista.
Will defer to @netixx for Jun and Cisco

**Comment by netixx** [comment]
I don't have a juniper that supports netconf 1.1.

From what I gather from https://datatracker.ietf.org/doc/html/draft-ietf-netconf-rfc4742bis#section-4.2, the chunk delimiter should always be on a line on it's own (somethink like `\n#(\d+)\n`).

**Comment by carlmontanari** [comment]
> From what I gather from https://datatracker.ietf.org/doc/html/draft-ietf-netconf-rfc4742bis#section-4.2

Hehe, yeah I mean... 100% agree with you... but I tend to take the rfc like speed limits -- a *suggestion* -- so would be great to test as much as we can before updating things! whatever we decide I will run all the tests against clab so we will have at least covered a good chunk of the most common stuff.

*I obviously never speed, that would be illegal and bad! 😅

**Comment by carlmontanari** [comment]
Sorry for delay, just pushed to main w/ the proposed fix!

Thanks a bunch everyone!
